ungnome/remembit

- package.json
- pnpm-lock.yaml
- src/router/index.ts
- src/views/LoginPage.vue
- Login page view
- vee-validate package
> feat: add login page

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- .gitignore
- firebase.json
- package.json
- pnpm-lock.yaml
- src/configs/newfile.json
- src/main.ts
- src/services/firebase.ts
- src/store/user.ts
- src/views/LoginPage.vue
- Pinia
- User Store for auth and user related data / functions
- Integrated login page with User Store
> feat: added firebase auth

- src/configs/newfile.json
- src/main.ts
- src/router/index.ts
- src/views/BookmarksPage.vue
- empty bookmarks page
- bookmarks page route
- route guard for routes that require authentication
> feat(bookmarks): add empty bookmarks page

- .eslintrc.js
- src/components/TheToolbar.vue
- src/views/BookmarksPage.vue
- Basic Toolbar component
- Avatar menu
- Logout button
- Toolbar title dynamically updates based on route name
> feat: added basic toolbar

- src/views/LoginPage.vue
- default to loading bookmarks page after login
> feat(login): adde default destination upon login

- package.json
- pnpm-lock.yaml
- src/store/bookmarks.ts
- src/views/BookmarksPage.vue
- Bookmarks store
- Mock bookmarks data using Faker
> feat(bookmarks): added bookmarks store with mock data

- src/views/BookmarksPage.vue
- Bookmarks list toolbar is now fixed at top of page
> fix(bookmarks): fixed bookmarks toolbar scrolling with content

- firebase.json
- firestore.indexes.json
- firestore.rules
- functions/.eslintrc.cjs
- functions/.gitignore
- functions/.npmrc
- functions/.prettierrc.cjs
- functions/package.json
- functions/pnpm-lock.yaml
- functions/src/auth/auth.ts
- functions/src/db/bookmarks.ts
- functions/src/db/event-history.ts
- functions/src/db/utils.ts
- functions/src/index.ts
- functions/tsconfig.dev.json
- functions/tsconfig.json
- package.json
- pnpm-lock.yaml
- src/services/firebase.ts
- src/store/bookmarks.ts
- src/store/user.ts
- src/views/BookmarksPage.vue
- tsconfig.json
- Firebase functions
- Integrated bookmarks and user stores with firebase
> feat: firestore backend integration

- src/components/BookmarksModalNew.vue
- src/store/bookmarks.ts
- src/views/BookmarksPage.vue
- Modal for creating bookmarks
> feat(bookmarks): added new bookmark modal

- package.json
- pnpm-lock.yaml
- src/components/BookmarksModalEdit.vue
- src/composables/bookmarkFormFields.ts
- src/store/bookmarks.ts
- src/views/BookmarksPage.vue
- src/views/LoginPage.vue
> feat: add edit bookmark modal

- src/views/BookmarksPage.vue
- removed tags list from bookmarks page
> feat: remove tag list from bookmark page

- .github/workflows/main.yml
- .github/workflows/reusable_deploy.yml
This is to split the firebase deployment steps into separate jobs.
> ci: split firebase deployment

- src/views/BookmarksPage.vue
- show tags under bookmark name
> feat: show tags on bookmarks list

- .github/workflows/ci.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
- .github/workflows/reusable_deploy.yml
- package.json
- refactored the ci workflows a bit
> ci: refactor workflows

- src/views/Bookmarks.vue
> feat(bookmarks): add search by name or tag

- src/components/BookmarkListEntry.vue
> fix: delete button

- .prettierrc.js
- src/components/BookmarkListEntry.vue
- src/components/BookmarksModalEdit.vue
- src/components/BookmarksModalNew.vue
- src/components/SettingsModal.vue
- src/composables/modalControls.ts
- src/views/Bookmarks.vue
- src/views/Profile.vue
- settings modal skeleton
- small UI tweaks
- moved modal controls to composable
- n/a
- n/a
> feat: settings skeleton

- src/App.vue
- src/components/SettingsModal.vue
- src/store/settings.ts
- src/store/user.ts
- settings stored in local storage
- n/a
- n/a
- n.a
> feat: add local storage for settings

- src/composables/toast.ts
- src/views/Login.vue
- toast message composable for handling presenting messages to the user
- handle login failures by presenting toast message to user
> fix(login): handle login failures

- vite.config.ts
- set pwa manifest start url to "/"
> fix: pwa start url

- src/components/ChangeEmailForm.vue
- src/components/YouAccountModalChangeEmail.vue
- src/components/YouAccountModalRoot.vue
- src/store/user.ts
> feat: change email
